### ISSUE TITLE
No default export

### ISSUE THREAD

**Issue by SWBennett06** [iamdustan/smoothscroll#113]
The readme indicates to import as follows:
`import smoothscroll from 'smoothscroll-polyfill`

However, this leaves smoothscroll undefined as there is no default export in the script. Instead, it is necessary to do a wildcard match of the whole module:
`import * as smoothscroll from 'smoothscroll-polyfill`

**Comment by jeremenichelli** [comment]
This might be a problem with the bundler configuration you are using. I've just created a test project, using webpack 4 (with no config at all) and did this:

```js
import smoothscroll from 'smoothscroll-polyfill'

smoothscroll.polyfill()
```

The resulting bundle looks like a charm in Safari. Make sure that you are not using a bundler that already supports ES modules notation with babel modules transpiling enabled, it's a common issue.

**Comment by iamdustan** [comment]
This actually is correct. We don’t export a valid ES module, we export a commonjs module. If you used webpack 4 with only es modules turned on it likely wouldn’t be as cordial.

**Comment by jeremenichelli** [comment]
I know that we are not _yet_ exposing `exports` notation, but the issue is about the statement not working as documented which it does.

I still don't follow, but to expose better a situation where the `import smoothscroll from 'smoothscroll-polyfill'` doesn't work as expected how the config or a reduced case should be?

@SWBennett06 can you provide some context on when are you having this issue? (bundler, bundler config, babel config, etc.)

**Comment by SWBennett06** [comment]
We are using Gulp to run tsify, which grabs our TypeScript config and transpiles the code.  It sounds like @jeremenichelli correctly diagnosed the issue I encountered and I simply hadn't run into this kind of issue before. 

I had thought the TS config option "allowsyntheticDefaultImports" would interpret the CommonJS export as "default", but it appears that I am incorrect.

**Comment by jeremenichelli** [comment]
Yes, this issue was a recurring thing in a lot of repositories because suddenly bundlers started to support `import` and `exports` by default, and babel presets traspiling them into `module.exports.default` was breaking lots of projects, didn't know about TS option though.

@SWBennett06 do you feel ok with closing this as it doesn't seem to be an issue on library? Or do you feel we should do something about it?

**Comment by iamdustan** [comment]
I think we can (and should) do something about it. I have a PR half-ready that should solve this for both browser globals, cjs, and es6 bundlers.

**Comment by jeremenichelli** [comment]
Cool @iamdustan, then let's leave it open and close it when we got that merged 💪

**Comment by rafaelrinaldi** [comment]
Just a heads up that this also breaks conditionally loading the polyfill via dynamic imports.

**Comment by entozoon** [comment]
Any update on this?
Problem still occurs as described, using Webpack v4.25 and ts-loader

**Comment by JohannesHoppe** [comment]
Same for all the Angular CLI users (webpack).

FYI
This works as expected and also supports server side rendering:

```ts
import * as smoothscroll from 'smoothscroll-polyfill';

if (typeof window !== 'undefined') {
  smoothscroll.polyfill();
}
```

**Comment by sbitproz** [comment]
@JohannesHoppe Thanks for the work around.  Any update on this?

**Comment by rafaelbiten** [comment]
If you also install the type definitions for the package with `npm i -S @types/smoothscroll-polyfill`,
you'll be able to import it directly:

```typescript
import smoothscroll from 'smoothscroll-polyfill'
smoothscroll.polyfill()
```

I'm using it on project bootstrapped with `create-react-app` with typescript. Tks for the polyfill btw!

**Comment by Necolanch** [comment]
Hey there. I am following the installation and usage instructions and get the following error:

Uncaught TypeError: Error resolving module specifier “smoothscroll-polyfill”. Relative module specifiers must start with “./”, “../” or “/”.

I have tried installing the type definitions as @rafaelbiten mentioned but still got the error. I am making a simple portfolio website with vanilla JavaScript.

**Comment by Mihajlo232** [comment]
> 

Same problem here!
